# TEAM 

# ESTE CÓDIGO MUESTRA LA CREACION DE UNA LISTA A QUE LE SE AGREGARA UN NUEVO ELEMENTO Y POSTERIORMENTE
# SE IMPRIMIRA EL RESULTADO PARA COMPROBAR QUE SE LA ACCION REALIZADA SI SE EJECUTO

# 2025 / 03/ 03 - V. 1. 2. 0

# TRABAJARON: CESAR ARTURO / CesarDAlvin

frutas = ["Uvas", "Guanabana", "Piña", "Fresa"] # SE CREA UNA LISTA CON FRUTAS


frutas.append("Mandarina") #LA FUNCION APPEND AGREGA UN NUEVO ELEMENTO A LAS LISTA DEFINIDA ANTERIORMENTE


print("Lista de frutas:", frutas) #LA FUNCION PRINT IMRPIME EN LA TERMINA PRIMERO, AL CADENA DE TEXTO "Lista de frutas" Y POSTERIORMENTE EL CONTENIDO DE LAS FRUTAS


for fruta in frutas:
    print("Tengo una", fruta)
